# Shougo Plugins
[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'Shougo/vimproc.vim'
build = 'make'

[[plugins]]
repo = 'Shougo/neosnippet.vim'
on_i = 1

[[plugins]]
repo = 'Shougo/neosnippet-snippets'

[[plugins]]
repo = 'Shougo/neocomplete.vim'
if = 'has("lua")'
on_i = 1

[[plugins]]
repo = 'Shougo/neoinclude.vim'

[[plugins]]
repo = 'Shougo/unite.vim'

[[plugins]]
repo = 'Shougo/context_filetype.vim'

# C/C++
[[plugins]]
repo = 'osyo-manga/vim-marching'

# lightline
[[plugins]]
repo = 'itchyny/lightline.vim'

# color scheme
[[plugins]]
repo = 'tomasr/molokai'

# QuickRun
[[plugins]]
repo = 'thinca/vim-quickrun'

# html/css
[[plugins]]
repo = 'othree/html5.vim'

[[plugins]]
repo = 'hail2u/vim-css3-syntax'

[[plugins]]
repo = 'gko/vim-coloresque'

# javascript
[[plugins]]
repo = 'jelera/vim-javascript-syntax'

# browser
[[plugins]]
repo = 'tyru/open-browser.vim'

# git
[[plugins]]
repo = 'tpope/vim-fugitive'

# json
[[plugins]]
repo = 'elzr/vim-json'

# toml
[[plugins]]
repo = 'cespare/vim-toml'

# markdown
[[plugins]]
repo = 'kannokanno/previm'

# LaTeX
[[plugins]]
repo = 'lervag/vimtex'

# arduino
[[plugins]]
repo = 'sudar/vim-arduino-syntax'

