# Shougo Plugins
[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'Shougo/vimproc.vim'
build = 'make'

[[plugins]]
repo = 'Shougo/denite.nvim'

[[plugins]]
repo = 'Shougo/deoplete.nvim'
hook_add = 'let g:deoplete#enable_at_startup = 1'

[[plugins]]
repo = 'Shougo/defx.nvim'

[[plugins]]
repo = 'roxma/nvim-yarp'

[[plugins]]
repo = 'roxma/vim-hug-neovim-rpc'

[[plugins]]
repo = 'Shougo/context_filetype.vim'

# python
#[[plugins]]
#repo = 'davidhalter/jedi-vim'
#
#[[plugins]]
#repo = 'andviro/flake8-vim'
#
#[[plugins]]
#repo = 'hynek/vim-python-pep8-indent'

# lightline
[[plugins]]
repo = 'itchyny/lightline.vim'

# color scheme
[[plugins]]
repo = 'tomasr/molokai'

# QuickRun
[[plugins]]
repo = 'thinca/vim-quickrun'

# git
[[plugins]]
repo = 'tpope/vim-fugitive'

# json
[[plugins]]
repo = 'elzr/vim-json'

# toml
[[plugins]]
repo = 'cespare/vim-toml'

# markdown
[[plugins]]
repo = 'kannokanno/previm'

# LaTeX
[[plugins]]
repo = 'lervag/vimtex'

# tmux
[[plugins]]
repo = 'christoomey/vim-tmux-navigator'

