# Shougo Plugins
[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'Shougo/vimproc.vim'
build = 'make'

[[plugins]]
repo = 'Shougo/deoplete.nvim'
hook_add = '''
  let g:deoplete#enable_at_startup = 1
  inoremap <expr><tab> pumvisible() ? "\<C-n>" :
        \ neosnippet#expandable_or_jumpable() ?
        \    "\<Plug>(neosnippet_expand_or_jump)" : "\<tab>"
'''
on_i = 1

[[plugins]]
repo = 'Shougo/neosnippet.vim'
hook_add = '''
  imap <C-k>     <Plug>(neosnippet_expand_or_jump)
  smap <C-k>     <Plug>(neosnippet_expand_or_jump)
  xmap <C-k>     <Plug>(neosnippet_expand_target)
  imap <expr><TAB> neosnippet#expandable_or_jumpable() ? "\<Plug>(neosnippet_expand_or_jump)" : pumvisible() ? "\<C-n>" : "\<TAB>"
  smap <expr><TAB> neosnippet#expandable_or_jumpable() ? "\<Plug>(neosnippet_expand_or_jump)" : "\<TAB>"
  if has('conceal')
    set conceallevel=2 concealcursor=niv
  endif
'''
on_i = 1
on_ft = ['snippet']
depends = ['neosnippet-snippets']

[[plugins]]
repo = 'Shougo/neosnippet-snippets'

[[plugins]]
repo = 'Shougo/denite.nvim'

[[plugins]]
repo = 'Shougo/defx.nvim'

[[plugins]]
repo = 'Shougo/context_filetype.vim'

# python
[[plugins]]
repo = 'davidhalter/jedi-vim'

[[plugins]]
repo = 'andviro/flake8-vim'

[[plugins]]
repo = 'hynek/vim-python-pep8-indent'

# lightline
[[plugins]]
repo = 'itchyny/lightline.vim'

# color scheme
[[plugins]]
repo = 'tomasr/molokai'

[[plugins]]
repo = 'ulwlu/elly.vim'

[[plugins]]
repo = 'cocopon/iceberg.vim'

# git
[[plugins]]
repo = 'tpope/vim-fugitive'

# json
[[plugins]]
repo = 'elzr/vim-json'

# toml
[[plugins]]
repo = 'cespare/vim-toml'

# tmux
[[plugins]]
repo = 'christoomey/vim-tmux-navigator'

# tex
[[plugins]]
repo = 'lervag/vimtex'

